# Build, run tests, deploy, and more: https://aka.ms/yaml.

trigger:
  batch: false
  branches:
    include:
    - master

# Enable PR triggers that target the master branch.
pr:
  autoCancel: true # Cancel previous builds on push.
  branches:
    include:
    - master

strategy:
  matrix:
    # Notes:
    #  Tags are encoded in the following way:
    #        <os> '-' <ghc-lib> '-' <compiler>
    #  Not every combination is tested
    #  - We do sampling to keep the number of builds reasonable.

    # +---------+-----------------+------------+
    # | OS      | ghc-lib flavour | GHC        |
    # +=========+=================+============+
    # | linux   | ghc-9.0.1       | ghc-8.10.1 |
    # | windows | ghc-9.0.1       | ghc-8.10.1 |
    # | macOS   | ghc-9.0.1       | ghc-8.10.1 |
    # +---------+-----------------+------------+
    linux-9.0.1-8.10.3:
      image: "ubuntu-latest"
      stack: "stack-exact.yaml"
    windows-9.0.1-8.10.3:
      image: "windows-latest"
      stack: "stack-exact.yaml"
    mac-9.0.1-8.10.3:
      image: "macOS-latest"
      stack: "stack-exact.yaml"

    # +---------+-----------------+------------+
    # | OS      | ghc-lib flavour | GHC        |
    # +=========+=================+============+
    # | linux   | ghc-8.10.4      | ghc-8.8.2  |
    # | windows | ghc-8.10.4      | ghc-8.8.2  |
    # | macOS   | ghc-8.10.4      | ghc-8.8.2  |
    # +---------+-----------------+------------+
    linux-8.10.4-8.8.2:
      image: "ubuntu-latest"
      stack: "stack-810-808-ghc-lib.yaml"
    windows-8.10.4-8.8.2:
      image: "windows-latest"
      stack: "stack-810-808-ghc-lib.yaml"
    mac-8.10.4-8.8.2:
      image: "macOS-latest"
      stack: "stack-810-808-ghc-lib.yaml"

    # +---------+-----------------+------------+
    # | OS      | ghc-lib flavour | GHC        |
    # +=========+=================+============+
    # | linux   | ghc-8.8.2       | ghc-8.8.2  |
    # | windows | ghc-8.8.2       | ghc-8.8.2  |
    # | macOS   | ghc-8.8.2       | ghc-8.8.2  |
    # +---------+-----------------+------------+
    # Note : These builds use native ghc libs, not ghc-lib-parser!
    linux-8.8.2-8.8.2-no-ghc-lib:
      image: "ubuntu-latest"
      stack: "stack-808-808-no-ghc-lib.yaml"
    windows-8.8.2-8.8.2-no-ghc-lib:
      image: "windows-latest"
      stack: "stack-808-808-no-ghc-lib.yaml"
    mac-8.8.2-8.8.2-no-ghc-lib:
      image: "macOS-latest"
      stack: "stack-808-808-no-ghc-lib.yaml"

    # +---------+-----------------+------------+
    # | OS      | ghc-lib flavour | GHC        |
    # +=========+=================+============+
    # | linux   | ghc-master      | ghc-8.8.2  |
    # | windows | ghc-master      | ghc-8.8.2  |
    # | macOS   | ghc-master      | ghc-8.8.2  |
    # +---------+-----------------+------------+
    linux-master-8.8.2:
      image: "ubuntu-latest"
      stack: "stack.yaml"
    windows-master-8.8.2:
      image: "windows-latest"
      stack: "stack.yaml"
    mac-master-8.8.2:
      image: "macOS-latest"
      stack: "stack.yaml"

    # These stopped working sometime around 2020-12-20.
    #
    # 2020-12-20T19:14:24.1846679Z HttpExceptionRequest Request {
    # 2020-12-20T19:14:24.1849204Z   host                 = "digitalassetsdk.bintray.com"
    # 2020-12-20T19:14:24.1863946Z   port                 = 443
    # 2020-12-20T19:14:24.1864712Z   secure               = True
    # 2020-12-20T19:14:24.1866437Z   requestHeaders       = [("User-Agent","Haskell pantry package")]
    # 2020-12-20T19:14:24.1867702Z   path                 = "/ghc-lib/ghc-lib-parser-8.8.1.20200122.tar.gz"
    # 2020-12-20T19:14:24.1868554Z   queryString          = ""
    # 2020-12-20T19:14:24.1869269Z   method               = "GET"
    # 2020-12-20T19:14:24.1870009Z   proxy                = Nothing
    # 2020-12-20T19:14:24.1870710Z   rawBody              = False
    # 2020-12-20T19:14:24.1871422Z   redirectCount        = 10
    # 2020-12-20T19:14:24.1872162Z   responseTimeout      = ResponseTimeoutDefault
    # 2020-12-20T19:14:24.1873297Z   requestVersion       = HTTP/1.1
    # 2020-12-20T19:14:24.1874127Z }

    # # +---------+-----------------+------------+
    # # | OS      | ghc-lib flavour | GHC        |
    # # +=========+=================+============+
    # # | linux   | da-ghc-8.8.1    | ghc-8.8.1  |
    # # | windows | da-ghc-8.8.1    | ghc-8.8.1  |
    # # | macOS   | da-ghc-8.8.1    | ghc-8.8.1  |
    # # +---------+-----------------+------------+
    # linux-da-8.8.1-8.8.1:
    #   image: "ubuntu-latest"
    #   stack: "stack-da-8.8.1.20200122.yaml"
    # windows-da-8.8.1-8.8.1:
    #   image: "windows-latest"
    #   stack: "stack-da-8.8.1.20200122.yaml"
    # mac-da-8.8.1-8.8.1:
    #   image: "macOS-latest"
    #   stack: "stack-da-8.8.1.20200122.yaml"

pool: {vmImage: '$(image)'}

steps:
  # macOS
  - bash: |
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      brew install autoconf automake
      brew upgrade gmp
    condition: eq( variables['Agent.OS'], 'Darwin' )
    displayName: Install brew

  - script: |
      curl -sSL https://get.haskellstack.org/ | sh
      set -e
      stack setup --stack-yaml=$(stack) > /dev/null
      curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s . '--cpp-include cbits' '--cpp-define GHCLIB_API_808'
      curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s . '--cpp-include cbits' '--cpp-define GHCLIB_API_810'
      curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s . '--cpp-include cbits' '--cpp-define GHCLIB_API_900'
      curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s . '--cpp-include cbits' '--cpp-define GHCLIB_API_HEAD'
      stack exec --stack-yaml=$(stack) --package extra --package optparse-applicative ghc -- -package extra -package optparse-applicative -Wall -Wno-name-shadowing -Werror -c CI.hs
      stack runhaskell --stack-yaml=$(stack) --package extra --package optparse-applicative CI.hs -- --stack-yaml=$(stack)
