# Build, run tests, deploy, and more: https://aka.ms/yaml.

trigger:
  batch: false
  branches:
    include:
    - master

# Enable PR triggers that target the master branch.
pr:
  autoCancel: true # Cancel previous builds on push.
  branches:
    include:
    - master

strategy:
  matrix:
    # Notes:
    #  Tags are encoded in the following way:
    #        <os> '-' <ghc-lib> '-' <compiler>
    #  Not every combination is tested
    #  - We do sampling to keep the number of builds reasonable.

    # +---------+-----------------+------------+
    # | OS      | ghc-lib flavour | GHC        |
    # +=========+=================+============+
    # | linux   | ghc-8.10.1      | ghc-8.10.1 |
    # | windows | ghc-8.10.1      | ghc-8.10.1 |
    # | macOS   | ghc-8.10.1      | ghc-8.10.1 |
    # +---------+-----------------+------------+
    linux-8.10.1-8.10.1:
      image: "Ubuntu 16.04"
      stack: "stack-exact.yaml"
    windows-8.10.1-8.10.1:
      image: "vs2017-win2016"
      stack: "stack-exact.yaml"
    mac-8.10.1-8.10.1:
      image: "macOS-10.14"
      stack: "stack-exact.yaml"

    # +---------+-----------------+------------+
    # | OS      | ghc-lib flavour | GHC        |
    # +=========+=================+============+
    # | linux   | ghc-8.10.1      | ghc-8.8.2  |
    # | windows | ghc-8.10.1      | ghc-8.8.2  |
    # | macOS   | ghc-8.10.1      | ghc-8.8.2  |
    # +---------+-----------------+------------+
    linux-8.10.1-8.8.2:
      image: "Ubuntu 16.04"
      stack: "stack-810-808-ghc-lib.yaml"
    windows-8.10.1-8.8.2:
      image: "vs2017-win2016"
      stack: "stack-810-808-ghc-lib.yaml"
    mac-8.10.1-8.8.2:
      image: "macOS-10.14"
      stack: "stack-810-808-ghc-lib.yaml"

    # +---------+-----------------+------------+
    # | OS      | ghc-lib flavour | GHC        |
    # +=========+=================+============+
    # | linux   | ghc-8.8.2       | ghc-8.8.2  |
    # | windows | ghc-8.8.2       | ghc-8.8.2  |
    # | macOS   | ghc-8.8.2       | ghc-8.8.2  |
    # +---------+-----------------+------------+
    # Note : These builds use native ghc libs, not ghc-lib-parser!
    linux-8.8.2-8.8.2-no-ghc-lib:
      image: "Ubuntu 16.04"
      stack: "stack-808-808-no-ghc-lib.yaml"
    windows-8.8.2-8.8.2-no-ghc-lib:
      image: "vs2017-win2016"
      stack: "stack-808-808-no-ghc-lib.yaml"
    mac-8.8.2-8.8.2-no-ghc-lib:
      image: "macOS-10.14"
      stack: "stack-808-808-no-ghc-lib.yaml"

    # +---------+-----------------+------------+
    # | OS      | ghc-lib flavour | GHC        |
    # +=========+=================+============+
    # | linux   | ghc-master      | ghc-8.8.2  |
    # | windows | ghc-master      | ghc-8.8.2  |
    # | macOS   | ghc-master      | ghc-8.8.2  |
    # +---------+-----------------+------------+
    linux-master-8.8.2:
      image: "Ubuntu 16.04"
      stack: "stack.yaml"
    windows-master-8.8.2:
      image: "vs2017-win2016"
      stack: "stack.yaml"
    mac-master--8.8.2:
      image: "macOS-10.14"
      stack: "stack.yaml"

    # +---------+-----------------+------------+
    # | OS      | ghc-lib flavour | GHC        |
    # +=========+=================+============+
    # | linux   | da-ghc-8.8.1    | ghc-8.8.1  |
    # | windows | da-ghc-8.8.1    | ghc-8.8.1  |
    # | macOS   | da-ghc-8.8.1    | ghc-8.8.1  |
    # +---------+-----------------+------------+
    linux-da-8.8.1-8.8.1:
      image: "Ubuntu 16.04"
      stack: "stack-da-8.8.1.20200122.yaml"
    windows-da-8.8.1-8.8.1:
      image: "vs2017-win2016"
      stack: "stack-da-8.8.1.20200122.yaml"
    mac-da-8.8.1-8.8.1:
      image: "macOS-10.14"
      stack: "stack-da-8.8.1.20200122.yaml"

pool: {vmImage: '$(image)'}

steps:
  # macOS
  - bash: |
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      brew install autoconf automake
      brew upgrade gmp
    condition: eq( variables['Agent.OS'], 'Darwin' )
    displayName: Install brew

  - script: |
      curl -sSL https://get.haskellstack.org/ | sh
      stack --stack-yaml=$(stack) setup > /dev/null
      curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s . '--cpp-include cbits' '--cpp-define GHCLIB_API_808'
      curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s . '--cpp-include cbits' '--cpp-define GHCLIB_API_810'
      curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s . '--cpp-include cbits' '--cpp-define GHCLIB_API_811'
      stack runhaskell --stack-yaml=$(stack) --package extra --package optparse-applicative CI.hs -- --stack-yaml=$(stack)
