resolver: lts-14.20
extra-deps: [ghc-lib-parser-0.20200102]
ghc-options:
    "$locals": -ddump-to-file -ddump-hi -Wall -Wno-name-shadowing
flags:
  ghc-lib-parser-ex:
    ghc-lib: true

# Packages MUST go at the end, since we append to it during execution
# of CI.hs.
packages:
- .
