resolver: nightly-2020-01-25 # ghc-8.8.2
extra-deps:
  - ghc-lib-parser-0.20200704
  - extra-1.7.3
ghc-options:
    "$locals": -ddump-to-file -ddump-hi -Wall -Wno-name-shadowing
flags:
  ghc-lib-parser-ex:
    auto: false
    no-ghc-lib: false

# Packages MUST go at the end, since we append to it during execution
# of CI.hs.
packages:
- .
